### ISSUE TITLE
Add Tutorial for GitHub Actions

### ISSUE THREAD

**Issue by SimeonEhrig** [QEDjl-project/IntegrationTests.jl#3]
The tutorial provide an example CI pipeline for GitLab CI with the following jobs

1. Set up search criteria for depending packages in an example project.
2. Execute the dependency graph search algorithm.
3. Generate example integration jobs.
4. Run the example integration jobs.

Generating and running the integration jobs is GitHub Actions specific. There is no direct support to generate dynamically new jobs but there is a solution which is only a small hack:

dynamic-job-workflow.yaml
```yaml
name: dynamic-matrix
on: [push, pull_request]

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - id: set-matrix
              run: echo "::set-output name=matrix::$(./generator.sh)"
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

    run-matrix:
        needs: generate
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: ${{ fromJson(needs.generate.outputs.matrix) }}
        steps:
            - run: echo ${{ matrix.package }}
```

generator.sh
```bash
#!/usr/bin/env bash

echo '["PkgA", "PkgB", "PkgC", "PkgD"]'
```

Original blog post: https://tomasvotruba.com/blog/2020/11/16/how-to-make-dynamic-matrix-in-github-actions/
